---
title: "Untitled"
output: html_document
---

```{r}
options(stringsAsFactors = F)
#21 genetic correlation matrix
ICA25 <- read.csv("D:/study/SummerIntern/ICA25.csv")
ICA25$Trait1 <- ICA25$Trait1-2142
ICA25$Trait2 <- ICA25$Trait2-2142
for(i in 1:21){
  temp = data.frame(Trait1=i, Trait2=i, rg=NA, se=NA, z=NA, p=NA)
  ICA25 = rbind(ICA25, temp)
}
for(i in 1:210){
  temp = ICA25[i,]
  temp_name = temp$Trait1[1]
  temp$Trait1[1] = temp$Trait2[1]
  temp$Trait2[1] = temp_name
  ICA25 = rbind(ICA25, temp)
}
```

```{r}
correlation_21 <- matrix(1, nrow=21, ncol=21)
rownames(correlation_21) = unique(ICA25$Trait1)
colnames(correlation_21) = sort(unique(ICA25$Trait2))
for(i in 1:210){
  temp=ICA25[i,]
  correlation_21[temp$Trait1[1],temp$Trait2[1]] = temp$rg[1]
  correlation_21[temp$Trait2[1],temp$Trait1[1]] = temp$rg[1]
}

#55 genetic correlation matrix
ICA100 <- read.csv("D:/study/SummerIntern/ICA100.csv")
ICA100$Trait1 <- ICA100$Trait1-2163
ICA100$Trait2 <- ICA100$Trait2-2163
for(i in 1:55){
  temp2 = data.frame(Trait1=i, Trait2=i, rg=NA, se=NA, z=NA, p=NA)
  ICA100 = rbind(ICA100, temp2)
}

for(i in 1:1485){
  temp2 = ICA100[i,]
  temp_name2 = temp2$Trait1[1]
  temp2$Trait1[1] = temp2$Trait2[1]
  temp2$Trait2[1] = temp_name2
  ICA100 = rbind(ICA100, temp2)
}
correlation_55 <- matrix(1, nrow=55, ncol=55)
rownames(correlation_55) = unique(ICA100$Trait1)
colnames(correlation_55) = sort(unique(ICA100$Trait2))

for(i in 1:1485){
  temp2=ICA100[i,]
  correlation_55[temp2$Trait1[1], temp2$Trait2[1]] = temp2$rg[1]
  correlation_55[temp2$Trait2[1], temp2$Trait1[1]] = temp2$rg[1]
}

heritability <- read.csv("D:/study/SummerIntern/summary.csv")
diag(correlation_21) <- heritability$Heritability[1:21]
diag(correlation_55) <- heritability$Heritability[22:76]

correlation_21
correlation_55
```




```{r}
#a <- c(1,3,4,6,8,14,16,17,18,20,23,30,32,34,35,38,41,42,50,51,52,53,54)#不在网络里
#b <- c(2,5,7,9,10,11,12,13,15,19,21,22,24,25,26,27,28,29,31,33,36,37,39,40,43,44,45,46,47,48,49,55)
a <- c(2,4,8,10,11,12,15,18,19)
b <- c(1,3,5,6,7,9,13,14,16,17,20,21)#在网络里
p <- 0
p1 <- 0
p2 <-0
s <- 0
for(i in a){
  for(j in b){
    p <- p+ correlation_21[i,j]
  }
}
for(i in a){
  for(j in a){
    p1 <- p1+ correlation_21[i,j]
  }
}
for(i in b){
  for(j in b){
    p2 <- p2+ correlation_21[i,j]
    s <-s+1
  }
}
#between
p/(length(a)*length(b))
#outside
p1/(length(a)*length(a))
#within
p2/(length(b)*length(b))
```
```{r}
a_55 <- c(1,3,4,6,8,14,16,17,18,20,23,30,32,34,35,38,41,42,50,51,52,53,54)#不在网络里
b_55 <- c(2,5,7,9,10,11,12,13,15,19,21,22,24,25,26,27,28,29,31,33,36,37,39,40,43,44,45,46,47,48,49,55)
a_21 <- c(2,4,8,10,11,12,15,18,19)#不在网络里
b_21 <- c(1,3,5,6,7,9,13,14,16,17,20,21)#在网络里
p <- c()
p1 <- c()
p2 <-c()
s <-0
#between
for(i in a_55){
  for(j in b_55){
    p <-c(p, correlation_55[i,j])
  }
}
for(i in a_21){
  for(j in b_21){
    p <-c(p, correlation_21[i,j])
  }
}
#outside
for(i in a_55){
  for(j in a_55){
    if(i <=j){
      p1 <-c(p1, correlation_55[i,j])
    }
  }
}
for(i in a_21){
  for(j in a_21){
    if(i<=j){
      p1 <-c(p1, correlation_21[i,j])
    }
  }
}
#within
for(i in b_55){
  for(j in b_55){
    if(i <= j){
      p2 <-c(p2, correlation_55[i,j])
    }
  }
}
for(i in b_21){
  for(j in b_21){
    if(i <= j){
      p2 <-c(p2, correlation_21[i,j])
    }
  }
}
#
p <-abs(p)
p1 <-(abs(p1))
p2 <-abs(p2)

box_function <- data.frame( heritability = c(p2,p,p1),group = factor(rep(c("within_triple_network" , "between_triple_network", "outside_triple_network"),times = c(length(p2),length(p),length(p1)))))
#within_triple_network = p2, between_triple_network = p, outside_triple_network = p1)
#boxplot()

mean(p)
mean(p1)
mean(p2)
```
```{r}
boxplot(heritability~group,data = box_function,width = c(1,1,1))
```

```{r}
a_55 <- c(1,3,4,6,8,14,16,17,18,20,23,30,32,34,35,38,41,42,50,51,52,53,54)#不在网络里
b_55 <- c(2,5,7,9,10,11,12,13,15,19,21,22,24,25,26,27,28,29,31,33,36,37,39,40,43,44,45,46,47,48,49,55)
a_21 <- c(2,4,8,10,11,12,15,18,19)#不在网络里
b_21 <- c(1,3,5,6,7,9,13,14,16,17,20,21)#在网络里
p_out <- c()
p_within <- c()
#outside
for(i in a_55){ p_out <- c(p_out, correlation_55[i,i])}
for(i in a_21){ p_out <- c(p_out, correlation_21[i,i])}
#within
for(i in b_55){ p_within <- c(p_within, correlation_55[i,i])}
for(i in b_21){ p_within <- c(p_within, correlation_21[i,i])}
box_function <- data.frame( heritability = c(p_within,p_out),group = factor(rep(c("within_triple_network" ,  "outside_triple_network"),times = c(length(p_within),length(p_out)))))
boxplot(heritability~group, data = box_function)
```

```{r}
library(flare)
out_21 <- sugm(correlation_21,method = "clime")
```



```{r}
seq_21 <-c(6,13,3,1,16,14,5,21,9,7,15,11,18,20,17,10,12,4,8,2,19)
seq_21_converse <- c(19,2,8,4,12,10,17,20,18,11,15,7,9,21,5,14,16,1,3,13,6)
outad_21 <- out_21$icov[[2]] 
outad_21 <-outad_21[seq_21,seq_21_converse]
rownames(outad_21) <- seq_21
colnames(outad_21) <- seq_21_converse
for(i in 1:21){
  for(j in 1:21){
    if(outad_21[i,j]!=0)outad_21[i,j] = -1
  }
}
```



```{r}
corrplot(corr = outad_21, method = "color",addgrid.col="grey",col = c("#FF6347","white"), tl.pos = "lt",tl.col = "black")
```

```{r}
out_55 <- sugm(correlation_55,method = "clime")
```


```{r}
seq_55_converse <- c(16,38,8,1,14,23,41,6,3,4,20,32,30,36,34,39,49,29,10,18,26,5,11,12,2,33,46,19,25,24,22,17,9,48,42,35,27,51,54,52,43,53,50,31,7,45,37,44,21,28,47,13,40,55,15)
seq_55 <-rev(seq_55_converse)
outad_55 <- out_55$icov[[4]] 
outad_55 <-outad_55[seq_55,seq_55_converse]
rownames(outad_55) <- seq_55
colnames(outad_55) <- seq_55_converse
for(i in 1:55){
  for(j in 1:55){
    if(outad_55[i,j]!=0)outad_55[i,j] = -1
  }
}
```



```{r}
corrplot(corr = outad_55, method = "color",addgrid.col="grey",col = c("#FF6347","white"), tl.pos = "lt",tl.col = "black")
```
```{r}
trait_list = 649:714
remov=which(trait_list==681|trait_list==682)
trait_list = trait_list[-remov]
length(trait_list)
```
